### ISSUE TITLE
error in the solution of task 2.2. d)

### ISSUE THREAD

**Issue by oliverp28** [tgweber/tiscript#22]
When solving problem 2.2 d) on page 66 (script) I came to a different conclusion. The given solution for interpreting the DFA is: "A accepts all words that begin with b or do not end with b." My view is: "A accepts all words that start with a or don't end with b". 

The content is in file kap_09.tex on line 30.

Best regards, Oliver Polak

**Comment by tgweber** [comment]
I guess there is a negation missing, does neither start nor end with b, which is equivalent to your solution. I will fix it asap. Thank you for the hint and please excuse the blip.

**Comment by tgweber** [comment]
I have to correct both of us. The correct solution is: "A accepts all words that do not start with b (which includes \epsilon) or do not end with b." Since \epsilon does not satrt with a, your answer is lacking. The old version had "does start with b", instead of "does not start with b", which is my version was also insufficient. I will correct it in the next merge.
